site_name: Sourcemeta Registry
site_url: https://registry.sourcemeta.com
repo_url: https://github.com/sourcemeta/registry
repo_name: sourcemeta/registry
copyright: Copyright &copy; Sourcemeta
edit_uri: edit/main/docs/
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/sourcemeta
    - icon: fontawesome/brands/github
      link: https://github.com/sourcemeta
  generator: false
  # See https://jimandreas.github.io/mkdocs-material/setup/setting-up-site-analytics/#custom-site-analytics
  analytics:
    provider: custom
    source: https://cdn.telemetrydeck.com/websdk/telemetrydeck.min.js
    attribute: "data-app-id"
    identifier: 4D73FC6D-E0BF-46A1-8D7A-F7C39B041189
# TODO: Add https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/
# TODO: Add https://squidfunk.github.io/mkdocs-material/setup/building-an-optimized-site/#built-in-optimize-plugin
plugins:
  - search
nav:
  - index.md
  - getting-started.md
  - configuration.md
  - library.md
  - commercial.md
  - Live Example Instance: https://schemas.sourcemeta.com
  - Community Support: https://github.com/sourcemeta/registry/discussions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_css:
  - assets/style.css
theme:
  language: en
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  name: material
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.share
    - content.action.edit
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: black
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: black
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
