function(sourcemeta_redocly_openapi_to_html)
  cmake_parse_arguments(SOURCEMETA_REDOCLY_OPENAPI_TO_HTML "" "REDOCLY;INPUT;OUTPUT" "DEPENDS" ${ARGN})

  if(NOT SOURCEMETA_REDOCLY_OPENAPI_TO_HTML_REDOCLY)
    message(FATAL_ERROR "You must pass the REDOCLY option to ${CMAKE_CURRENT_FUNCTION}")
  endif()

  if(NOT SOURCEMETA_REDOCLY_OPENAPI_TO_HTML_INPUT)
    message(FATAL_ERROR "You must pass the INPUT option to ${CMAKE_CURRENT_FUNCTION}")
  endif()

  if(NOT SOURCEMETA_REDOCLY_OPENAPI_TO_HTML_OUTPUT)
    message(FATAL_ERROR "You must pass the OUTPUT option to ${CMAKE_CURRENT_FUNCTION}")
  endif()

  find_program(NODE_BIN NAMES node REQUIRED)

  set(SOURCEMETA_REDOCLY_OPENAPI_TO_HTML_ALL_DEPS "${SOURCEMETA_REDOCLY_OPENAPI_TO_HTML_INPUT}")
  if(SOURCEMETA_REDOCLY_OPENAPI_TO_HTML_DEPENDS)
    list(APPEND SOURCEMETA_REDOCLY_OPENAPI_TO_HTML_ALL_DEPS ${SOURCEMETA_REDOCLY_OPENAPI_TO_HTML_DEPENDS})
  endif()

  add_custom_command(
    OUTPUT "${SOURCEMETA_REDOCLY_OPENAPI_TO_HTML_OUTPUT}"
    COMMAND "${NODE_BIN}" "${SOURCEMETA_REDOCLY_OPENAPI_TO_HTML_REDOCLY}"
      build-docs --disableGoogleFont --output "${SOURCEMETA_REDOCLY_OPENAPI_TO_HTML_OUTPUT}"
      "${SOURCEMETA_REDOCLY_OPENAPI_TO_HTML_INPUT}"
    DEPENDS ${SOURCEMETA_REDOCLY_OPENAPI_TO_HTML_ALL_DEPS})
endfunction()
