name: Sourcemeta Registry CI

on:
  pull_request:

concurrency:
  group: registry-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update && sudo apt-get install --yes codespell
      - uses: actions/checkout@v4
      - run: codespell docs *.markdown docs/*.md

  test:
    strategy:
      fail-fast: false
      matrix:
        edition:
          - name: enterprise
          - name: pro
          - name: starter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Dependencies
      - name: Install Hurl
        run: |
          curl --location --remote-name https://github.com/Orange-OpenSource/hurl/releases/download/${{ env.HURL_VERSION }}/hurl_${{ env.HURL_VERSION }}_amd64.deb
          sudo apt install ./hurl_${{ env.HURL_VERSION }}_amd64.deb
          rm hurl_${{ env.HURL_VERSION }}_amd64.deb
        env:
          HURL_VERSION: 5.0.1

      - name: Build Registry
        run: >
          docker build
          --tag registry-${{ matrix.edition.name }} .
          --file Dockerfile
          --build-arg SOURCEMETA_REGISTRY_EDITION=${{ matrix.edition.name }}
          --progress plain

      - name: Build Sandbox (headless)
        run: docker compose --file test/sandbox/compose.yaml build
        env:
          SOURCEMETA_REGISTRY_EDITION: ${{ matrix.edition.name }}
          SOURCEMETA_REGISTRY_CONFIGURATION: headless
      - name: Up Sandbox (headless)
        run: docker compose --file test/sandbox/compose.yaml up --detach --wait
        env:
          SOURCEMETA_REGISTRY_EDITION: ${{ matrix.edition.name }}
          SOURCEMETA_REGISTRY_CONFIGURATION: headless
      - name: Test Sandbox (headless)
        run: make test-e2e PRESET=Release EDITION=${{ matrix.edition.name }}
        env:
          SANDBOX_CONFIGURATION: headless
      - name: Down Sandbox (headless)
        run: docker compose --file test/sandbox/compose.yaml down
        env:
          SOURCEMETA_REGISTRY_EDITION: ${{ matrix.edition.name }}
          SOURCEMETA_REGISTRY_CONFIGURATION: headless

      - name: Build Sandbox (full)
        run: docker compose --file test/sandbox/compose.yaml build
        env:
          SOURCEMETA_REGISTRY_EDITION: ${{ matrix.edition.name }}
          SOURCEMETA_REGISTRY_CONFIGURATION: full
      - name: Up Sandbox (full)
        run: docker compose --file test/sandbox/compose.yaml up --detach --wait
        env:
          SOURCEMETA_REGISTRY_EDITION: ${{ matrix.edition.name }}
          SOURCEMETA_REGISTRY_CONFIGURATION: full
      - name: Test Sandbox (full)
        run: make test-e2e PRESET=Release EDITION=${{ matrix.edition.name }}
        env:
          SANDBOX_CONFIGURATION: full
      - name: Down Sandbox (full)
        run: docker compose --file test/sandbox/compose.yaml down
        env:
          SOURCEMETA_REGISTRY_EDITION: ${{ matrix.edition.name }}
          SOURCEMETA_REGISTRY_CONFIGURATION: full

      # Public instance
      - run: >
          docker build .
          --file public/Dockerfile
          --progress plain
          --build-arg SOURCEMETA_REGISTRY=registry-${{ matrix.edition.name }}
        if: matrix.edition.name == 'enterprise'

  website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs build --config-file mkdocs.yml --strict --site-dir ./build/website
