name: Sourcemeta Registry CI

on:
  pull_request:

concurrency:
  group: registry-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        edition:
          - name: enterprise
          - name: pro
          - name: starter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Dependencies
      - run: pipx install clang-format==19.1.0
      - uses: sourcemeta/jsonschema@v9.3.1
      - name: Install Hurl
        run: |
          curl --location --remote-name https://github.com/Orange-OpenSource/hurl/releases/download/${{ env.HURL_VERSION }}/hurl_${{ env.HURL_VERSION }}_amd64.deb
          sudo apt install ./hurl_${{ env.HURL_VERSION }}_amd64.deb
          rm hurl_${{ env.HURL_VERSION }}_amd64.deb
        env:
          HURL_VERSION: 5.0.1

      # Linting
      - run: make configure PRESET=Release INDEX=OFF SERVER=OFF EDITION=${{ matrix.edition.name }}
      - run: make lint PRESET=Release EDITION=${{ matrix.edition.name }}

      # Testing
      - run: make test-schemas PRESET=Release EDITION=${{ matrix.edition.name }}
      - run: docker build --tag registry-${{ matrix.edition.name }} . --file Dockerfile.${{ matrix.edition.name }} --progress plain
      - run: docker compose --file test/sandbox/compose-${{ matrix.edition.name }}.yaml build
      - run: docker compose --file test/sandbox/compose-${{ matrix.edition.name }}.yaml up --detach --wait
      - run: make test-e2e PRESET=Release EDITION=${{ matrix.edition.name }}
      - run: docker compose --file test/sandbox/compose-${{ matrix.edition.name }}.yaml down
